name: job summaries

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo1
        run: echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
      - name: Generate list using Markdown
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Write Summary from Action
        uses: actions/github-script@v6.1.0
        with:
          script: |
            await core.summary
            .addHeading('Test Results')
            .addTable([
              [{data: 'File', header: true}, {data: 'Result', header: true}],
              ['foo.js', 'Pass'],
              ['bar.js', 'Fail'],
              ['test.js', 'Pass']
            ])
            .addLink('View staging deployment', 'https://github.com')
            .write()
